---
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-accounts:persistence:file:default:1.0"
  path: "./data/accounts.json"

- descriptor: "pip-services-accounts:controller:default:default:1.0"
  options:
    login_as_email: true

- descriptor: "pip-services-accounts:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
